/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TextTimerImport } from './routes/textTimer'
import { Route as TemplateDigitalImport } from './routes/templateDigital'
import { Route as TemplateAnalogImport } from './routes/templateAnalog'
import { Route as SetTimerImport } from './routes/setTimer'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TextTimerRoute = TextTimerImport.update({
  id: '/textTimer',
  path: '/textTimer',
  getParentRoute: () => rootRoute,
} as any)

const TemplateDigitalRoute = TemplateDigitalImport.update({
  id: '/templateDigital',
  path: '/templateDigital',
  getParentRoute: () => rootRoute,
} as any)

const TemplateAnalogRoute = TemplateAnalogImport.update({
  id: '/templateAnalog',
  path: '/templateAnalog',
  getParentRoute: () => rootRoute,
} as any)

const SetTimerRoute = SetTimerImport.update({
  id: '/setTimer',
  path: '/setTimer',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/setTimer': {
      id: '/setTimer'
      path: '/setTimer'
      fullPath: '/setTimer'
      preLoaderRoute: typeof SetTimerImport
      parentRoute: typeof rootRoute
    }
    '/templateAnalog': {
      id: '/templateAnalog'
      path: '/templateAnalog'
      fullPath: '/templateAnalog'
      preLoaderRoute: typeof TemplateAnalogImport
      parentRoute: typeof rootRoute
    }
    '/templateDigital': {
      id: '/templateDigital'
      path: '/templateDigital'
      fullPath: '/templateDigital'
      preLoaderRoute: typeof TemplateDigitalImport
      parentRoute: typeof rootRoute
    }
    '/textTimer': {
      id: '/textTimer'
      path: '/textTimer'
      fullPath: '/textTimer'
      preLoaderRoute: typeof TextTimerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setTimer': typeof SetTimerRoute
  '/templateAnalog': typeof TemplateAnalogRoute
  '/templateDigital': typeof TemplateDigitalRoute
  '/textTimer': typeof TextTimerRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setTimer': typeof SetTimerRoute
  '/templateAnalog': typeof TemplateAnalogRoute
  '/templateDigital': typeof TemplateDigitalRoute
  '/textTimer': typeof TextTimerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/setTimer': typeof SetTimerRoute
  '/templateAnalog': typeof TemplateAnalogRoute
  '/templateDigital': typeof TemplateDigitalRoute
  '/textTimer': typeof TextTimerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setTimer'
    | '/templateAnalog'
    | '/templateDigital'
    | '/textTimer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/setTimer' | '/templateAnalog' | '/templateDigital' | '/textTimer'
  id:
    | '__root__'
    | '/'
    | '/setTimer'
    | '/templateAnalog'
    | '/templateDigital'
    | '/textTimer'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SetTimerRoute: typeof SetTimerRoute
  TemplateAnalogRoute: typeof TemplateAnalogRoute
  TemplateDigitalRoute: typeof TemplateDigitalRoute
  TextTimerRoute: typeof TextTimerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SetTimerRoute: SetTimerRoute,
  TemplateAnalogRoute: TemplateAnalogRoute,
  TemplateDigitalRoute: TemplateDigitalRoute,
  TextTimerRoute: TextTimerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/setTimer",
        "/templateAnalog",
        "/templateDigital",
        "/textTimer"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/setTimer": {
      "filePath": "setTimer.tsx"
    },
    "/templateAnalog": {
      "filePath": "templateAnalog.tsx"
    },
    "/templateDigital": {
      "filePath": "templateDigital.tsx"
    },
    "/textTimer": {
      "filePath": "textTimer.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
